MippSamplePortal/Models/Workorder.cs
using System;
using System.Collections.Generic;

namespace MippSamplePortal.Models;

public partial class Workorder
{
    public int Id { get; set; }

    public string? OrderNumber { get; set; }

    public string? OrderDate { get; set; }

    public string? AssignedTo { get; set; }

    public string? AssignedToCompany { get; set; }

    public string? AssignedToAddress { get; set; }

    public string? AssignedToPhone { get; set; }

    public string? AssignedToEmailAddress { get; set; }

    public string? ExpectedStartDate { get; set; }

    public string? ExpectedEndDate { get; set; }

    public string? ServiceRequestNumber { get; set; }

    public string? Status { get; set; }

    public string? Description { get; set; }

    public string? AdditionalComments { get; set; }

    public string? ExpectedNoOfHoursToComplete { get; set; }

    public string? WorkPerformedBy { get; set; }

    public string? WorkCompletedAndMaterialsUsed { get; set; }

    public string? TotalHoursSpent { get; set; }

    public string? PropertyName { get; set; }

    public string? PropertyAddress { get; set; }

    public string? PropertyManager { get; set; }

    public string? PropertyManagerPhone { get; set; }

    public string? PropertyManagerEmail { get; set; }

    public string? TenantName { get; set; }

    public string? TenantEmailAddress { get; set; }

    public string? TenantPhoneNumber { get; set; }

    public string? UnitName { get; set; }

    public string? UnitAddress { get; set; }

    public string? Note { get; set; }

    public string? PreferredTime { get; set; }

    public string? EnterCondition { get; set; }

    public string? PermissionNote { get; set; }

    public string? EntryDate { get; set; }

    public string? TimeEntered { get; set; }

    public string? TimeDeparted { get; set; }

    public string? EntryNote { get; set; }

    public string? WorkorderCompiledBy { get; set; }

    public string? WorkorderApprovedBy { get; set; }

    public string? DateOfApproval { get; set; }

    public string? Priority { get; set; }

    public string? CostOfLabor { get; set; }

    public string? CostOfMaterials { get; set; }

    public string? TaxesPaid { get; set; }

    public string? Total { get; set; }

    public int? ClientId { get; set; }

    public int? VendorId { get; set; }

    public bool? IsDelete { get; set; }

    public string? CreatedBy { get; set; }

    public string? ModifideBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }
}

MippSamplePortal/Controllers/WorkorderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using MippSamplePortal.Models;
using MippSamplePortal.ViewModel;
using Newtonsoft.Json;

namespace MippSamplePortal.Controllers
{
    [Authorize]
    public class WorkorderController : Controller
    {
        private readonly MippTestContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHostEnvironment _hostEnvironment;

        public WorkorderController(MippTestContext context, IConfiguration configuration, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> Index(string email)
        {
            email = User.Identity.Name;
            WorkorderRequest workorderRequest = new WorkorderRequest();
            workorderRequest.ClientID = _context.Clients.FirstOrDefault(x => x.Email == email).Id;
            workorderRequest.AdditionalComments = "";
            workorderRequest.Status = "";

            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }

            IEnumerable<WorkorderMasterModel> workorder;
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(workorderRequest), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(apiUrl + "Workorders/GetWorkorders", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    try
                    {
                        workorder = JsonConvert.DeserializeObject<IEnumerable<WorkorderMasterModel>>(apiResponse);
                        //ViewBag.VendorId = vendorId;
                        ViewBag.Workorder = workorder;
                        //ViewBag.msg = msg;

                        ViewData["GridData"] = workorder;
                        ViewBag.GridData = workorder;
                        ViewBag.Tax = "";
                        ViewBag.Subtotal = "";
                        ViewBag.Total = "";
                        ViewBag.ClientID = workorderRequest.ClientID;
                        TempData["Email"] = email;
                        ViewBag.Email = email;
                        foreach (var item in workorder)
                        {
                            if(_context.VendorLists.FirstOrDefault(x => x.Id == item.VendorId) != null)
                            {
                                item.Vendor = _context.VendorLists.FirstOrDefault(x => x.Id == item.VendorId).VendorName;

                            }
                            else
                            {
                                item.Vendor = "NA";
                            }
                        }
                        return View(workorder.ToList());
                    }
                    catch (Exception ex)
                    {

                    }
                }
            }
            return NotFound();
        }

        public ActionResult Create(string email, string vendorEmail)
        {
            ViewBag.ClientID = _context.Clients.FirstOrDefault(x => x.Email == email).ClientId;
            int cId = ViewBag.ClientID;
            var emailAddresses = new List<string>();
            var statuses = new List<string>();
            if (vendorEmail == null)
            {
                var vendors = _context.VendorLists.Where(x => x.ClientId == cId);
                foreach (var item in vendors)
                {
                    emailAddresses.Add(item.VendorEmail);
                }
                ViewBag.Vendors = vendors;
            }
            var vendor = _context.VendorLists.Where(x => x.VendorEmail == vendorEmail);
            var status = _context.ClientStatuses.Where(x => x.ClientId == cId);

            foreach (var item in status)
            {
                statuses.Add(item.Status);
            }
            
            ViewBag.EmailAddresses = emailAddresses;
            ViewBag.Status = statuses;

            ViewBag.Vendor = vendor.ToList();
            //ViewBag.Vendors = new List<string>
            //{
                
            //}
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(int clientId, [Bind] WorkorderMasterModel workorder)
        {
            workorder.ClientId = clientId;
            workorder.Status = "Assigned";
            workorder.EnterCondition = "Call for availiablity";
            workorder.VendorId = _context.VendorLists.FirstOrDefault(x=> x.VendorEmail == workorder.AssignedToEmailAddress).Id;
            var email = _context.Clients.FirstOrDefault(x => x.Id == clientId).Email;
            WorkorderRequest workorderRequest = new WorkorderRequest();
            workorderRequest.ClientID = workorder.ClientId;
            workorderRequest.AdditionalComments = workorder.Status;
            workorderRequest.Status = "";

            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }


            IEnumerable<WorkorderMasterModel> workorders;
            int count = 0;
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(workorderRequest), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(apiUrl + "Workorders/GetWorkorders", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    try
                    {
                        workorders = JsonConvert.DeserializeObject<IEnumerable<WorkorderMasterModel>>(apiResponse);
                        count = 0;
                    }
                    catch (Exception ex)
                    {

                    }
                }
            }


            try
            {
                
                //workorder.Id = count + 1;


                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(workorder), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync(apiUrl + "Workorders/PostWorkorder", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        

                        using (var httpClient1 = new HttpClient())
                        {
                            StringContent content1 = new StringContent(JsonConvert.SerializeObject(workorder), Encoding.UTF8, "application/json");

                            using (var response1 = await httpClient.PostAsync(apiUrl + "SendEmail/SendWorkorderUpdateEmail", content))
                            {
                                string apiResponse1 = await response.Content.ReadAsStringAsync();
                                //receivedReservation = JsonConvert.DeserializeObject<Reservation>(apiResponse);
                                //return true;
                                return RedirectToAction("Index", new { email = email });
                            }
                        }

                    }
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }




        public async Task<IActionResult> Edit(int? id, string email)
        {
            if (id == null)
            {
                return View(null);
            }
            IEnumerable<ClientStatus> workorderStatus = null;
            IEnumerable<WorkorderTask> workorderWorkDescription = null;
            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }

            WorkorderRequest workorderRequest = new WorkorderRequest();
            workorderRequest.Id = (int)id;
            //workorderRequest.ClientID = 0;
            workorderRequest.Status = String.Empty;

MippSamplePortal/Views/Workorder/Edit.cshtml
@model MippSamplePortal.Models.Workorder

@{
    ViewData["Title"] = "Edit";
    var id = ViewData["VendorId"];
    var email = ViewBag.Email;
    var workorderId = ViewBag.Id;
    var clientId = ViewBag.clientId;
    var descriptions = ViewBag.Descriptions;
    var status = "";

}

<h1>Edit</h1>

<h4>Workorder</h4>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.OrderNumber)
        @Html.HiddenFor(model => model.OrderDate)
        <div class="form-group">
            @Html.LabelFor(model => model.AssignedTo, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignedTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignedTo, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.AssignedToCompany)
        @Html.HiddenFor(model => model.AssignedToAddress)
        @Html.HiddenFor(model => model.AssignedToEmailAddress)
        @Html.HiddenFor(model => model.ExpectedStartDate)
        @Html.HiddenFor(model => model.ExpectedEndDate)
        @Html.HiddenFor(model => model.ServiceRequestNumber)
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Description)
        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalComments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdditionalComments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdditionalComments, "", new { @class = "text-danger" })
            </div>
        </div>
       
        @Html.HiddenFor(model => model.ExpectedNoOfHoursToComplete)
        @Html.HiddenFor(model => model.WorkPerformedBy)
        @Html.HiddenFor(model => model.WorkCompletedAndMaterialsUsed)
        @Html.HiddenFor(model => model.TotalHoursSpent)
        @Html.HiddenFor(model => model.PropertyName)
        @Html.HiddenFor(model => model.PropertyAddress)
        @Html.HiddenFor(model => model.PropertyManager)
        @Html.HiddenFor(model => model.PropertyManagerPhone)
        @Html.HiddenFor(model => model.PropertyManagerEmail)
        @Html.HiddenFor(model => model.TenantName)
        @Html.HiddenFor(model => model.TenantEmailAddress)
        @Html.HiddenFor(model => model.TenantPhoneNumber)
        @Html.HiddenFor(model => model.UnitName)
        @Html.HiddenFor(model => model.UnitAddress)
        @Html.HiddenFor(model => model.Note)
        @Html.HiddenFor(model => model.PreferredTime)
        @Html.HiddenFor(model => model.EnterCondition)
        @Html.HiddenFor(model => model.PermissionNote)
        @Html.HiddenFor(model => model.EntryDate)
        @Html.HiddenFor(model => model.TimeEntered)
        @Html.HiddenFor(model => model.TimeDeparted)
        @Html.HiddenFor(model => model.EntryNote)
        @Html.HiddenFor(model => model.WorkorderCompiledBy)
        @Html.HiddenFor(model => model.WorkorderApprovedBy)
        @Html.HiddenFor(model => model.DateOfApproval)
        @Html.HiddenFor(model => model.Priority)
        @Html.HiddenFor(model => model.CostOfLabor)
        @Html.HiddenFor(model => model.CostOfMaterials)
        @Html.HiddenFor(model => model.TaxesPaid)
        @Html.HiddenFor(model => model.Total)
        @Html.HiddenFor(model => model.ClientId)
        @Html.HiddenFor(model => model.VendorId)



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div id="descriptions">
    @foreach (var description in descriptions)
    {
        <div class="row d-flex ml-lg-2 ml-sm-1" id="description" style="display: flex;">
            <div class="form-group" style="width: max-content; display:none">
                <label class="control-label">Id: </label>
                <input value="@description.Id" id="idText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <input value="@description.DescriptionOfWorkToComplete" id="descriptionText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Expected Hours to Complete: </label>
                <input value="@description.ExpectedHours" class="form-control" id="hoursText" style="background-color:white; display:inline; margin-left: 1%; width: 83%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <textarea  id="commentText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;">@description.AdditionalComment</textarea> 
            </div>
        </div>

    }
    <div class="row d-flex ml-lg-2 ml-sm-1" id="description" style="display: flex;">
            <div class="form-group" style="width: max-content; display:none">
                <label class="control-label">Id: </label>
                <input  id="idText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <input  id="descriptionText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Expected Hours to Complete: </label>
                <input class="form-control" id="hoursText" style="background-color:white; display:inline; margin-left: 1%; width: 83%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <textarea  id="commentText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;"></textarea> 
            </div>
        <button id="add-row-btn" onclick="AddLine()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Add
            </button>&nbsp;&nbsp;
        <button id="remove-btn" onclick="RemoveLine()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Delete
            </button>&nbsp;&nbsp;
        <button id="save-row-btn" onclick="SaveDescription()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Save
            </button>
    </div>

</div>









@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function AddLine() {
            var newRow = `<div class="form-group" style="width: max-content; display:none">
                <label class="control-label">Id: </label>
                <input  id="idText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <input  id="descriptionText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;" />
            </div>
            
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Expected Hours to Complete: </label>
                <input class="form-control" id="hoursText" style="background-color:white; display:inline; margin-left: 1%; width: 83%;" />
            </div>
            <div class="form-group" style="width: max-content;">
                <label class="control-label">Work completed & Materials used: </label>
                <textarea  id="commentText" class="form-control" style="background-color:white; display:inline;margin-left: 1%; width: 62%;"></textarea> 
            </div>
        <button id="add-row-btn" onclick="AddLine()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Add
            </button>&nbsp;&nbsp;
        <button id="remove-btn" onclick="RemoveLine()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Delete
            </button>&nbsp;&nbsp;
        <button id="save-row-btn" onclick="SaveDescription()" class="btn btn-primary" style="    width: fit-content;
    height: fit-content;
    margin-top: 3%;">
                Save
            </button>
        `;
            $("#descriptions").append(newRow);


        }
        function RemoveLine() {
            document.getElementById("descriptions").removeChild(document.getElementById("descriptions").children[1]);
        }

        function SaveDescription() {
            var descriptions = document.querySelectorAll("#descriptionText");
            var hours = document.querySelectorAll("#hoursText");
            console.log("564", descriptions);
            console.log("565", hours);

            var testArr = [];

            for (let i = 0; i < document.querySelectorAll("#descriptionText").length; i++) {
                if (document.querySelectorAll("#idText")[i] == null || document.querySelectorAll("#idText")[i] == undefined || document.querySelectorAll("#idText")[i] == "") {
                    testArr.push({
                        Id: -1,
                        DescriptionOfWorkToComplete: document.querySelectorAll("#descriptionText")[i].value,
                        ExpectedHours: document.querySelectorAll("#hoursText")[i].value,
                        AdditionalComment: document.querySelectorAll("#commentText")[i].value,
                        WorkorderId: @workorderId,
                        IsDelete: false,
                        CreatedBy: "",
                        ModifideBy:"",
                        CreatedAt: null,
                        ModifiedAt: null
                        });
                }
                testArr.push({
                    Id: document.querySelectorAll("#idText")[i].value,
                    DescriptionOfWorkToComplete: document.querySelectorAll("#descriptionText")[i].value,
                    ExpectedHours: document.querySelectorAll("#hoursText")[i].value,
                    AdditionalComment: document.querySelectorAll("#commentText")[i].value,
                    WorkorderId: @workorderId,
                    IsDelete: false,
                    CreatedBy: "",
                    ModifideBy:"",
                    CreatedAt: null,
                    ModifiedAt: null
                    });
            }
            console.log(testArr);

            $.post('@Url.Action("PostWorkorderTasks","Workorder")', { workorderTasks: testArr },
                function () {
                    showNotification('success', 'Workorder description updated!');
                }).fail(function(response){
                    showNotification('warning', response)
                });

        }

        function showNotification(type, message) {
            $.notify(message, type);
        }

</script>
}

MippSamplePortal/Views/Workorder/Index.cshtml
@using Syncfusion.EJ2;
@using Syncfusion.EJ2.Navigations;
@using Syncfusion.EJ2.Grids;
@model IEnumerable<MippSamplePortal.ViewModel.WorkorderMasterModel>

@{
    ViewData["Title"] = "Index";
    var email = ViewBag.Email;
}
<html>
<body>
    <h1>Workorders</h1>

    <p>
        <a asp-action="Create" asp-route-email="@email">Create New</a>
    </p>

    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">

        <div class="btn-group mr-2" role="group" aria-label="First group">
            <button id="create" class="btn btn-default">Create New</button>

            <button id="edit" class="btn btn-default" disabled="true">Update</button>
            @*        <button id="details" class="btn btn-default" disabled="true">Create Bill</button>
            <button id="settings" class="btn btn-default">Settings</button>
            <button id="assigned" class="btn btn-default">Assigned</button>
            <button id="completed" class="btn btn-default">Completed</button>*@
        </div>

    </div>


    <div id="Grid"></div>
</body>

@section Scripts {

    <script src="~/dist/js/notify.js"></script>
    <script src="~/dist/js/notify.min.js"></script>

    <script>

        function showNotification(type, message) {
            $.notify(message, type);
        }

        function rowSelected() {
            var grid = document.getElementsByClassName('e-grid')[0].ej2_instances[0].getSelectedRecords();
            //var selectedRecords = grid.getSelectedRecords();
            //var selectedRecordsCount = selectedRecords.length;
            console.log(document.getElementsByClassName('e-grid')[0].ej2_instances[0].getSelectedRecords());
            console.log("selectedRecord:", grid);


            if (grid != null) {

                document.getElementById("edit").disabled = false;
            }
            else {
                document.getElementById("edit").disabled = true;
            }

        }


        document.getElementById('edit').onclick = function () {

            var grid = document.getElementsByClassName('e-grid')[0].ej2_instances[0];
            console.log(grid);
            var selectedRecords = grid.getSelectedRecords();
            var id = selectedRecords[0].Id;

            var url = document.location.origin + "/Workorder/Edit/" + id;
            window.location.replace(url);

        };

        //document.getElementById('settings').onclick = function () {


        //    var vendorID = @ViewBag.VendorId

        //    var url = document.location.origin + "/Settings/Index?vendorId=" + vendorID;
        //    window.location.replace(url);

        //};

        //document.getElementById('assigned').onclick = function () {


        //    var vendorID = @ViewBag.VendorId

        //            var url = document.location.origin + "/Workorders/AssignedWorkorders?vendorId=" + vendorID;
        //    window.location.replace(url);

        //};
        //document.getElementById('completed').onclick = function () {


        //    var vendorID = @ViewBag.VendorId

        //    var url = document.location.origin + "/Workorders/CompletedWorkorders?vendorId=" + vendorID;
        //    window.location.replace(url);

        //};

        document.getElementById('create').onclick = function () {
            var grid = document.getElementsByClassName('e-grid')[0].ej2_instances[0].currentViewData[0];
           

            var id = grid.VendorId;
            var url = document.location.origin + "/Workorders/Create/" + id;
            window.location.replace(url);


        };


                //document.getElementById('details').onclick = function () {

                //    var grid = document.getElementsByClassName('e-grid')[0].ej2_instances[0];
                //    var selectedRecords = grid.getSelectedRecords();

                //    if (selectedRecords[0].Status == "Approved") {
                //        var vendorID = selectedRecords[0].VendorId;
                //        var id = selectedRecords[0].Id;
                //        var url = document.location.origin + "/Bills/Index?vendorID=" + vendorID + "&woID=" + id;

                //        window.location.replace(url);
                //    }
                //    else {
                //        showNotification('warning', 'Workorder is not approved for billing!');
                //    }
                //};
    </script>

    <ejs-grid id="Grid" allowPaging="true" allowSorting="true"
          allowPdfExport="true" allowExcelExport="true" allowselection=" true" rowSelected="rowSelected" datasource="@ViewBag.GridData">
        <e-grid-pagesettings pageSize="5"></e-grid-pagesettings>
        @*<e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true"></e-grid-editSettings>
    <e-grid-filtersettings type="Menu"></e-grid-filtersettings>
    <e-grid-loadingIndicator indicatorType="Shimmer"></e-grid-loadingIndicator>
    <e-grid-selectionsettings persistSelection="true" type="Multiple" checkboxOnly="true"></e-grid-selectionsettings>*@
        <e-grid-columns>
            <e-grid-column type="checkbox" width="50" />
            <e-grid-column field="ServiceRequestNumber" header - text="Request Number" width="75" text-align="right"> </e-grid-column>
            <e-grid-column field="PropertyAddress" header-text="Property Address" width="80"> </e-grid-column>
            <e-grid-column field="Vendor" header-text="Vendor" width="80"> </e-grid-column>
            <e-grid-column field="Status" header-text="Status" text-align="right" width="75"> </e-grid-column>
            <e-grid-column field="ExpectedEndDate" header-text="End Date" text-align="right" width="75"> </e-grid-column>
        </e-grid-columns>
    </ejs-grid>
}
</html>