MippVendorPortal/Controllers/JoinController.cs
using dotless.Core.Parser.Infrastructure;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MippPortalWebAPI.Helpers;

using MippVendorPortal.Areas.Identity.Data;
using MippVendorPortal.Models;
using MippVendorPortal.ViewModel;
using MippVendorPortal.Helpers;
using Newtonsoft.Json;
using System.Text;
using AspNetUser = MippVendorPortal.Models.AspNetUser;

namespace MippVendorPortal.Controllers
{
    public class JoinController : Controller
    {
        private readonly MippVendorTestContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHostEnvironment _hostEnvironment;
        private readonly UserManager<MippVendorPortalUser> _userManager;
        private readonly SignInManager<MippVendorPortalUser> _signInManager;

        public JoinController(MippVendorTestContext context, UserManager<MippVendorPortalUser> userManager,
            SignInManager<MippVendorPortalUser> signInManager,IConfiguration configuration, IHostEnvironment hostEnvironment)
        {
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;

        }
        // GET: Join

        public async Task<IActionResult> Index(string e, string cId, string rvId)
        {
            CryptographyHelper cryptographyHelper = new CryptographyHelper();
            var mail = cryptographyHelper.DecryptString(e);

            var mailpresent = _context.Vendors.FirstOrDefault(x => x.VendorEmail == mail);

            //get vendor details from vendorList
            VendorList vendorSaved = null;
            VendorRequest vendorRequest = new VendorRequest();
            vendorRequest.email = mail;
            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }
            try
            {
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(vendorRequest), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync(apiUrl + "Vendors/GetVendorData", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        vendorSaved = JsonConvert.DeserializeObject<VendorList>(apiResponse);

                       
                     
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            if (mailpresent == null)
            {
                if (e != null && cId != null)
                {
                    ViewBag.Email = mail;
                    ViewBag.ClientId = Convert.ToInt32(cryptographyHelper.DecryptString(cId));
                    ViewBag.RootVendorId = Convert.ToInt32(cryptographyHelper.DecryptString(rvId));
                    ViewBag.Company = vendorSaved.BusinessName;
                    ViewBag.FullName = vendorSaved.VendorName;
                    ViewBag.PhoneNo = vendorSaved.VendorPhone;
                }

                return View();
            }
            ViewBag.ClientId = cId;
            ViewBag.VendorId = rvId;
            ViewBag.Email = mail;
            ViewBag.msg = "Your account already exists!";
            var model = new AcceptInvitationLoginModel();
            model.Email=mail;
            model.ClientId = Convert.ToInt32(cryptographyHelper.DecryptString(cId));
            model.VendorId = Convert.ToInt32(cryptographyHelper.DecryptString(cId));
            model.Password=string.Empty;
            return View("AcceptInvitationLogin",model);

        }

        // GET: Join/Details/5
        public async Task<IActionResult> Accept(AcceptInvitationLoginModel model)
        {
            try
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    ViewData["Email"] = model.Email;
                    TempData["Email"] = model.Email;
                    
                }
                else
                {
                    ViewBag.Msg("Unable to login Wron Credintials");

                    return View(model);
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
            var username = User.Identity.Name;
            
            

            var vendor = _context.Vendors.First(x => x.VendorEmail == username);
            vendor.RootVendorId = model.VendorId;
            await _context.SaveChangesAsync();



            MippVendorPortal.Models.VendorClient vendorClient = new MippVendorPortal.Models.VendorClient();
            vendorClient.Id = _context.VendorClients.Count() + 1;
            vendorClient.VendorId = vendor.Id;
            vendorClient.ClientId = model.ClientId;
            if (_context.VendorClients.FirstOrDefault(x => x.VendorId == vendorClient.Id && x.ClientId == vendorClient.ClientId) == null)
            {
                _context.VendorClients.Add(vendorClient);
                await _context.SaveChangesAsync();
            }
            else
            {
                return BadRequest("Hey! You are already registered..");
            }


            VendorInvite vendorInvite = new VendorInvite();
            vendorInvite.Id = vendor.Id;
            vendorInvite.VendorId = model.VendorId;
            vendorInvite.VendorEmail = model.Email;
            vendorInvite.ClientId = model.ClientId;
            vendorInvite.JoinedDate = DateTime.Today.ToString();

            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }

            try
            {
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(vendorInvite), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync(apiUrl + "SendEmail/UpdateVendorInvite", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        
                        return RedirectToAction("Index", "Workorders");
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }


        }

       

        public async Task<IActionResult> Register(int id, [Bind("VendorEmail, VendorPassword, VendorName, VendorCompany, VendorPhone, ClientId, RootVendorId")] VendorClientViewModel vendor)
        {
            try
            {
                MippVendorPortalUser aspNetUser = new MippVendorPortalUser()
                {
                    Email = vendor.VendorEmail,
                    UserName = vendor.VendorEmail,
                    EmailConfirmed = true
                };
                var result = await _userManager.CreateAsync(aspNetUser, vendor.VendorPassword);
                if(!result.Succeeded) 
                {
                    throw new Exception(result.Errors.First().Description);
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
            VendorInvite vendorInvite = new VendorInvite();
            vendorInvite.Id = int.Parse(vendor.RootVendorId);
            vendorInvite.VendorId = int.Parse(vendor.RootVendorId);
            vendorInvite.VendorEmail = vendor.VendorEmail;
            vendorInvite.ClientId = int.Parse(vendor.ClientId);
            vendorInvite.JoinedDate = DateTime.Today.ToString();
            //check here whether vendorclient relationship already exists or not

            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }

            
            try
            {
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(vendorInvite), Encoding.UTF8, "application/json");

MippVendorPortal/Views/Join/AcceptInvitationLogin.cshtml
@model MippVendorPortal.Models.AcceptInvitationLoginModel

@{
    ViewData["Title"] = "Index";
    // var tabHeaderOne = new TabHeader { Text = "Lokalizace" };
    //var tabHeaderTwo = new TabHeader { Text = "Cenik" };
    Layout = "~/Views/Shared/_Layout.cshtml";
    var vendorId = ViewBag.VendorId;

}

<div class="row d-flex justify-content-center">
    <p><h4>UserName @Model.Email Already Exist.Login to accept invitation</h4></p>
    <div class="col-md-6 col-xs-12">
        
        <div class="card">
           
                
            
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to accept the invitation</p>
                <form asp-controller="Join" asp-action="Accept" method="post">
                    <hr />
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                   
                    <input asp-for="ClientId" class="form-control" hidden="true"/>
                    <input asp-for="VendorId" class="form-control" hidden="true" />
                

                    <div class="input-group mb-3">
                        <input asp-for="Email" class="form-control" autocomplete="username" aria-required="true" placeholder="name@example.com" />
                                              <span asp-validation-for="Email" class="text-danger"></span>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input asp-for="Password" class="form-control" autocomplete="current-password" aria-required="true" placeholder="password" />
                                          <span asp-validation-for="Password" class="text-danger"></span>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    



                    <div class="row">

                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>

                    </div>

                </form>
               @* <div class="row d-flex">
                    <p>
                        <a id="forgot-password" asp-page="./ForgotPassword">Forgot your password?</a>
                    </p>
                    <p>
                        <a asp-page="./Register">Register as a new user</a>
                    </p>
                    @*<p>
                    <a id="resend-confirmation" asp-page="./ResendEmailConfirmation">Resend email confirmation</a>
                    </p>
                </div>*@

            </div>

        </div>
    </div>
</div>








@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>

        if (ViewBag.msg)
            alert(msg);
    </script>
}

MippVendorPortal/Views/Join/Index.cshtml
@model MippVendorPortal.ViewModel.VendorClientViewModel

@{
    var isAgreed = false;

}

<div class="row d-flex justify-content-center">
    <div class="register-box col-md-6">
        <div class="card">
            <div class="card-body register-card-body">
                <p class="login-box-msg" style="text-align-last: center;">
                    <div class="register-logo">
                        <a href="../Views/Homes/Index.cshtml"><b>Vendor</b> &nbsp;Portal</a>
                    </div>

                </p>
                <form asp-controller="Join" asp-action="Register" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" asp-for="VendorName" placeholder="Your name here" value="@ViewBag.FullName" readonly>
                        <div class="input-group-append">
                            <div class="input-group-text" >
                                <span class="fas fa-id-card"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Email" asp-for="VendorEmail" value="@ViewBag.Email" readonly>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" asp-for="VendorCompany" placeholder="Company or Organization" value="@ViewBag.Company" readonly>
                        <div class="input-group-append">
                            <div class="input-group-text" >
                                <span class="fas fa-briefcase"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" asp-for="VendorPhone" placeholder="Phone Number"  readonly>
                        <div class="input-group-append">
                            <div class="input-group-text" >
                                <span class="fas fa-phone"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="password" id="password" class="form-control" asp-for="VendorPassword" placeholder="Password" required onchange="validatePassword()">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        
                    </div>
                    <span id="message" style="color:red"> </span>


                    <div class="input-group mb-3">
                        <input type="password" class="form-control" id="ConfirmPassword" placeholder="Confirm Password" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>

                    </div>
                    <span id="ConfirmMessage" style="color:red"> </span>


                    <div class="input-group mb-3" style="display:none">
                        <input type="text" class="form-control" asp-for="ClientId" value="@ViewBag.ClientId">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-address-card"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3" style="display:none">
                        <input type="text" class="form-control" asp-for="RootVendorId" value="@ViewBag.RootVendorId">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-address-card"></span>
                            </div>
                        </div>
                    </div>



                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                                <label for="agreeTerms">
                                    I agree to the <a href="#">terms</a>
                                </label>
                            </div>
                        </div>

                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block" id="submitButton" disabled>Accept</button>
                        </div>

                    </div>
                </form>

            </div>

        </div>
    </div>
    </div>

    











@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
    <script src="../wwwroot/plugins/jquery/jquery.min.js"></script>

    <script src="../wwwroot/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="../wwwroot/dist/js/adminlte.min.js?v=3.2.0"></script>


    <script>
        var PassVal = false;
        var ConfPass = false;
        var AgreeTerms = false;
        $("#check").click(function () {
            alert("Congrats! Registration successfull!!")
        });
        var checkbox = document.getElementById("agreeTerms");

        checkbox.addEventListener('change', function () {
            var submitButton = $('#submitButton');
            if (this.checked) {
                console.log("Checkbox is checked..");
                AgreeTerms = true;
                if (AgreeTerms && ConfPass && PassVal)
                submitButton.prop('disabled', false);
                

            } else {
                console.log("Checkbox is not checked..");
                AgreeTerms=false;
                submitButton.prop('disabled', true);
            }
        });
        
        function validatePassword()
        {
            confirmPass.value=""
            ConfPass=false;
            var expression = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{6,20}$/;
            var pass = document.getElementById("password").value;
            var submitButton = $('#submitButton');
            if (pass.match(expression))
            {
                document.getElementById("message").innerHTML = "";
                PassVal=true;
                if (AgreeTerms && ConfPass && PassVal)
                    submitButton.prop('disabled', false);
                
            }
            else
            {
                document.getElementById("message").innerHTML = "Password restrictions<br>  - At least 6 charactors <br> -  at least 1 capital and 1 small letter<br>   - at least 1 number<br>  - at least 1 spec char";
                PassVal = false;
                submitButton.prop('disabled', true);
                

            }
        };
        


        var confirmPass = document.getElementById("ConfirmPassword");
        confirmPass.addEventListener('change', function () {

            var pass = document.getElementById("password").value;
            var Confpassword = document.getElementById("ConfirmPassword").value;
            var submitButton = $('#submitButton');
            if (pass === Confpassword) {
                document.getElementById("ConfirmMessage").innerHTML = "";
                ConfPass=true
                if (AgreeTerms && ConfPass && PassVal)
                    submitButton.prop('disabled', false);
            }
            else {
                document.getElementById("ConfirmMessage").innerHTML = "Password does'not match";
                ConfPass = false;
                submitButton.prop('disabled', true);
            }
        });
    </script>
}