MippVendorPortal/Models/Workorder.cs
using System;
using System.Collections.Generic;

namespace MippVendorPortal.Models;

public partial class Workorder
{
    public int Id { get; set; }

    public string? OrderNumber { get; set; }

    public string? OrderDate { get; set; }

    public string? AssignedTo { get; set; }

    public string? AssignedToCompany { get; set; }

    public string? AssignedToAddress { get; set; }

    public string? AssignedToPhone { get; set; }

    public string? AssignedToEmailAddress { get; set; }

    public string? ExpectedStartDate { get; set; }

    public string? ExpectedEndDate { get; set; }

    public string? ServiceRequestNumber { get; set; }

    public string? Status { get; set; }

    public string? Description { get; set; }

    public string? AdditionalComments { get; set; }

    public string? ExpectedNoOfHoursToComplete { get; set; }

    public string? WorkPerformedBy { get; set; }

    public string? WorkCompletedAndMaterialsUsed { get; set; }

    public string? TotalHoursSpent { get; set; }

    public string? PropertyName { get; set; }

    public string? PropertyAddress { get; set; }

    public string? PropertyManager { get; set; }

    public string? PropertyManagerPhone { get; set; }

    public string? PropertyManagerEmail { get; set; }

    public string? TenantName { get; set; }

    public string? TenantEmailAddress { get; set; }

    public string? TenantPhoneNumber { get; set; }

    public string? UnitName { get; set; }

    public string? UnitAddress { get; set; }

    public string? Note { get; set; }

    public string? PreferredTime { get; set; }

    public string? EnterCondition { get; set; }

    public string? PermissionNote { get; set; }

    public string? EntryDate { get; set; }

    public string? TimeEntered { get; set; }

    public string? TimeDeparted { get; set; }

    public string? EntryNote { get; set; }

    public string? WorkorderCompiledBy { get; set; }

    public string? WorkorderApprovedBy { get; set; }

    public string? DateOfApproval { get; set; }

    public string? Priority { get; set; }

    public string? CostOfLabor { get; set; }

    public string? CostOfMaterials { get; set; }

    public string? TaxesPaid { get; set; }

    public string? Total { get; set; }

    public int? ClientId { get; set; }

    public int? VendorId { get; set; }
}

MippVendorPortal/Controllers/WorkordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

using Azure.Storage.Blobs;
using dotless.Core.Parser.Functions;
using dotless.Core.Parser.Infrastructure;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.JsonPatch.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;




using MippVendorPortal.Models;
using MippVendorPortal.ViewModel;
using Newtonsoft.Json;
using MippVendorPortal.Helpers;


namespace MippVendorPortal.Controllers
{
    [Authorize]
    public class WorkordersController : Controller
    {
        private readonly MippVendorTestContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHostEnvironment _hostEnvironment;

        public WorkordersController(MippVendorTestContext context, IConfiguration configuration, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
            
        }

        public async Task<IEnumerable<WorkorderTask>> GetWorkorderTasks(int workorderID)
        {
            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }
            IEnumerable<WorkorderTask> workDescriptions;

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(workorderID), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(apiUrl + "Workorders/GetWorkorderDescriptions", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    workDescriptions = JsonConvert.DeserializeObject<IEnumerable<WorkorderTask>>(apiResponse);
                    try
                    {
                        return workDescriptions;
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                }
            }
        }


        [HttpGet("GetWorkOrderStatus")]
        public async Task<ActionResult<string>> GetWorkOrderStatus(int workorderId)
        {
            try
            {
                var env = _hostEnvironment.EnvironmentName;
                string apiUrl = string.Empty;
                if (env == "Development")
                {
                    // Configure services for development environment
                    apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                    //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
                }
                else
                {
                    // Configure services for local environment
                    apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
                }

                string status = String.Empty;
                using (var httpClient = new HttpClient())
                {
                    

                    using (var response = await httpClient.GetAsync(apiUrl + "Workorders/GetWorkorderStatus?workorderId=" + workorderId))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        status = JsonConvert.DeserializeObject<string>(apiResponse);
                       
                    }
                }

                return Ok(status);
            }
            catch
            {
                return BadRequest();
            }
        }

        //[HttpPost]
        //public async void PostWorkorderDescriptions(IEnumerable<WorkorderWorkDescription> workDescriptions)
        //{
        //    var one = workDescriptions.First();
        //    foreach (var item in workDescriptions)
        //    {
        //        WorkorderWorkDescription workDescription = new WorkorderWorkDescription();
        //        var existing = _context1.WorkorderWorkDescriptions.FirstOrDefault(x => x.Id == item.Id);
        //        if (existing != null)
        //        {
        //            //workDescription.WorkorderId = item.WorkorderId;
        //            existing.DescriptionOfWorkCompletedMaterialsUsed = item.DescriptionOfWorkCompletedMaterialsUsed;
        //            existing.HoursSpent = item.HoursSpent;
        //            _context1.WorkorderWorkDescriptions.Update(existing);
        //            _context1.SaveChanges();
        //        }
        //        else
        //        {
        //            workDescription.WorkorderId = item.WorkorderId;
        //            workDescription.DescriptionOfWorkCompletedMaterialsUsed = item.DescriptionOfWorkCompletedMaterialsUsed;
        //            workDescription.HoursSpent = item.HoursSpent;
        //            _context1.WorkorderWorkDescriptions.Add(workDescription);
        //            _context1.SaveChanges();
        //        }
        //    }
        //    //send email for workorder update here
        //    var env = _hostEnvironment.EnvironmentName;
        //    string apiUrl = string.Empty;
        //    if (env == "Development")
        //    {
        //        // Configure services for development environment
        //        apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
        //        //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
        //    }
        //    else
        //    {
        //        // Configure services for local environment
        //        apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
        //    }
        //    var workorder = _context1.Workorders.FirstOrDefault(x => x.Id == one.Id);
        //    using (var httpClient1 = new HttpClient())
        //    {
        //        StringContent content1 = new StringContent(JsonConvert.SerializeObject(workorder), Encoding.UTF8, "application/json");

        //        using (var response1 = await httpClient1.PostAsync(apiUrl + "SendEmail/SendWorkorderStatusUpdateEmail", content1))
        //        {
        //            string apiResponse1 = await response1.Content.ReadAsStringAsync();
        //            //receivedReservation = JsonConvert.DeserializeObject<Reservation>(apiResponse);
        //            //return true;
        //            //return RedirectToAction("Index", new { rootVendorId = workorder.VendorId, msg = "" });
        //        }
        //    }
        //}


        //public IActionResult SubmitComments(int workorderId, string text, string email)
        //{
        //    var commentsObj = new WorkorderComment();
        //    commentsObj.Email = email;
        //    commentsObj.Text = text;
        //    commentsObj.WorkorderId = workorderId;

        //    _context1.WorkorderComments.Add(commentsObj);
        //    _context1.SaveChanges();
        //    return RedirectToAction("Edit", new { id = workorderId });
        //    //send email on adding comments


        //}
        //public IActionResult OverlayPartial(int woid)
        //{
        //    ViewBag.Id = woid;
        //    ViewBag.Email = _context1.Vendors.FirstOrDefault
        //                        (x => x.Id == _context1.Workorders.FirstOrDefault(x => x.Id == woid).VendorId).Email;
        //    return View("_CommentsView");
        //    //return PartialView("_FeedbackPartial");
        //}

        

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var username = User.Identity.Name;
            var vendor = _context.Vendors.First(x=>x.VendorEmail== username);
            var rootvendorId = vendor.RootVendorId;
            WorkorderRequest workorderRequest = new WorkorderRequest
            {
                VendorID = rootvendorId,
                AdditionalComments = "",
                Status = ""
            };

            var env = _hostEnvironment.EnvironmentName;
            string apiUrl = string.Empty;
            if (env == "Development")
            {
                // Configure services for development environment
                apiUrl = _configuration.GetValue<string>("LocalEnvironmentAPIUrl");
                //apiUrl = _configuration.GetValue<string>("DevEnvironmentAPIUrl");
            }
            else
            {
                // Configure services for local environment
                apiUrl = _configuration.GetValue<string>("ProdEnvironmentAPIUrl");
            }



            IEnumerable<ViewModel.WorkorderMasterModel> workorder;
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(workorderRequest), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(apiUrl + "Workorders/GetWorkorders", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    try
                    {
                        workorder = JsonConvert.DeserializeObject<IEnumerable<ViewModel.WorkorderMasterModel>>(apiResponse);
                        ViewBag.VendorId = rootvendorId;

MippVendorPortal/Views/Workorders/_WorkDescription.cshtml
@using MippVendorPortal.Models
@model List<WorkorderWorkDescriptionDTO>;

<div>
  
    


    @for (var i = 0; i < Model.Count; i++)
            {
                @if (Model[i].IsDelete == true)
                {
                                <div style="border:solid 1px gray; border-radius: 20px; box-shadow: 10px 10px 5px lightblue; padding: 1%;" class="mx-2 my-3" id="WorkDescription">
                                    <p>The recorde is Deleted By @Model[i].ModifideBy At @Model[i].ModifiedAt </p>
                                 </div>
                                 <form id="UpdateWorkOrderform" enctype="multipart/form-data">
                                <input id="DescriptionID"  hidden  value=@Model[i].Id />
                                <input id="WorkorderId"  hidden  value=@Model[i].WorkorderId />
                                <input id="TaskId"  hidden />
                                <input id="IsDelete" value=@Model[i].IsDelete hidden value="False" />
                                <input id="CreatedBy" value=@Model[i].CreatedBy hidden type="text" />
                                <input id="ModifideBy" value=@Model[i].ModifideBy  hidden type="text" />
                                <input id="CreatedAt" value=@Model[i].CreatedAt hidden type="datetime" />
                                <input id="ModifiedAt" value=@Model[i].ModifiedAt hidden type="datetime" />
                                 <input id="WorkMaterials"  hidden type="datetime" />
                                <input id="WorkMaterials" hidden type="datetime" />
                                <input id="DescriptionOfWork"  hidden type="datetime" />
                                <input id="HourSpent" hidden type="datetime" />
                                <input id="AdditionalComment"  hidden type="datetime" />
                                <input id="AdditionalComment"  hidden type="datetime" />
                                <input id="file"  hidden type="datetime" />
                                </form>

                }
                else
                {
                        <div style="border:solid 1px gray; border-radius: 20px; box-shadow: 10px 10px 5px lightblue; padding: 1%;" class="mx-2 my-5" id="WorkDescription">
                             <span><a id="toggle_@i" class="fa-sharp fa-solid fa-chevron-up fa-rotate-180" data-bs-toggle="collapse" role="button"  data-bs-target="#details_@i" aria-expanded="false" aria-controls="details_@i" ></a></span>
                            <form id="UpdateWorkOrderform" enctype="multipart/form-data">
                            <div class="form-row">
                                <input id="DescriptionID" name="Id"  hidden  value=@Model[i].Id />
                                <input id="WorkorderId" name="WorkorderId"  hidden  value=@Model[i].WorkorderId />
                                <input id="TaskId" name="TaskId"  hidden />
                                <input id="IsDelete" name="IsDelete"  hidden value="False" />
                                <input id="CreatedBy" name="CreatedBy" value='@Model[i].CreatedBy'  hidden type="text" />
                                <input id="ModifideBy" name="ModifideBy"   hidden type="text" />
                                <input id="CreatedAt" name="CreatedAt" value='@Model[i].CreatedAt' hidden type="datetime" />
                                <input id="ModifiedAt"  hidden type="datetime" />
                               

                               
                                <div class="form-group col-md-3" >
                                    <label>Work Performed By</label>
                                    <input type="text" value='@Model[i].WorkPerformedBy' required class="form-control" id="WorkPerformedBy" name="WorkPerformedBy">
                                </div>

                                <div class="form-group col-md-3">
                                    <label>Description Of Work</label>
                                    <input type="text" value='@Model[i].DescriptionOfWork' required class="form-control"id="DescriptionOfWork" name="DescriptionOfWork">
                                </div>
                                <div class="form-group col-md-3">
                                    <label>Work Materials</label>
                                    <input type="text" value='@Model[i].WorkMaterials' required class="form-control" id="WorkMaterials" name="WorkMaterials">
                                </div>
                                <div class="form-group col-md-2">
                                    <label>HourSpent</label>
                                    <input type="number" value='@Model[i].HourSpent' required id="HourSpent" name="HourSpent" step="0.5" class="form-control" >

                                </div>
                            </div>
                            <div class="collapse" id="details_@i">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Additional Comment</label>
                                    <textarea  class="form-control" id="AdditionalComment" name="AdditionalComment">@Model[i].AdditionalComment</textarea>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="row">
                                        <label>Upload Documents</label>
                                        <input type="file" name="file" id="file" class="form-control " style="margin-right: 1%; width: 100%;" multiple />
                                    </div>
                                                                            

                                </div>

                            </div>
                            
                            <div>
                                @if (Model[i].Files.Count > 0)
                                {
                                    <label>Uploaded documents</label>
                                    <div class="row d-flex col-sm-12" style="overflow-x:scroll" id="uploadedDocuments">
                                        @foreach (var item in Model[i].Files)
                                        {
                                            <div class="m-1">
                                                <img src="@item.url"  style="float: left;
                                                                    width:  100px;
                                                                    height: 100px;
                                                                    object-fit: cover;" onclick="getImageData(this)">
                                                <div style="align-items:center">
                                                <a href="@item.url" class="m-1" ><i class="fas fa-download"></i></a>
                                                <a href=# class="m-1" onclick='DeleteFile("@item.blobname")'  ><i class="fas fa-trash"></i></a>
                                                </div>
                                            </div>

                                        }

                                    </div>
                                }
                            </div>
                            </div>
                            </form>
                            <div class="row">
                                        <button id="btnUpdate" onclick="Update(@i)"  class="btn btn-primary m-1">Save</button>
                                        <button id="remove-btn" onclick="Delete(@i)"  class="btn btn-danger m-1">Mark As Delete</button>
                            </div>
                                                                 
                        </div>
                }
            }
    </div>
    
</div>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script src="~/dist/js/notify.js"></script>
<script src="~/dist/js/notify.min.js"></script>



<script type="text/javascript">
    

    window.onload = function () {
        $('#loading').hide();
     
     


    }
        


    //function DeleteLine(element) {
    //    //$(element).parent().css("filter","blur(2px)");
    //    $(element).parent().parent().find("*").each(function () {
    //        //$(this).css("filter","blur(2px)");
    //        $(this).attr('disabled', 'disabled');
    //        $(this).attr('disabled', 'disabled');
    //    });
        
    //    var message = `<span style="color: red"> Marked for deletion <span>`;
    //    element.parentElement.parentElement.style.boxShadow = "10px 10px 5px red";
    //    $(element).parent().parent().append(message);
    //}

   

    function showNotification(type, message) {
        $.notify(message, type);
    }



    
        
        


    @*        $.post('@Url.Action("EditPost","Workorders")', { workorder: workorderArr },
    //            function () {
    //                showNotification('success', 'Workorder updated!');


    //                //$.ajax({
    //                //    url: '/Workorders/PostWorkorderWorkDescription',
    //                //    type: 'POST',
    //                //    data: formData,
    //                //    success: function (response) {
    //                //        showNotification('success', 'Workorder updated!');


    //                //    },
    //                //    error: function (error) {
    //                //        showNotification('warning', error);
    //                //    }
    //                //});
    //        });
    //}*@

    
</script>